version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AKIA5QUUKEBP35UEY4X7
          aws-region: ap-south-1
          aws-secret-access-key: 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
          from: bucket
          to: 's3://nodejs-app-625'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          to: 's3://nodejs-app-625'
workflows:
  s3-example:
    jobs:
      - build
