version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - aws-s3/sync:
          from: build
          to: "s3://nodejs-app-625"
          profile: my-aws-profile
          region: us-east-1
          clean: true
          cache_control: "max-age=604800"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
