version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm install
      - run: npm build
  deploy:
    working_directory: ~/project
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Deploy to S3
          command: |
            apt-get update
            apt-get install -y python-pip
            pip install awscli
            aws s3 cp . s3://nodejs-app-625/ --recursive
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
