version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: bucket
          to: 's3://nodejs-app-625/'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          to: 's3://nodejs-app-625'
workflows:
  s3-example:
    jobs:
      - build
